@@
   &airflow-common
-  image: apache/airflow:2.9.0-python3.11
+  build: .
@@
   airflow-webserver:
-    <<: *airflow-common
-    command: webserver
+    <<: *airflow-common
+    command: webserver
@@
   airflow-scheduler:
-    <<: *airflow-common
-    command: scheduler
+    <<: *airflow-common
+    command: scheduler
